<a href="https://colab.research.google.com/github/KIMDOKYOUNG/DeepLearning/blob/master/chapter5/chapter_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## 밑바닥부터 시작하는 딥러닝 1 뽀개기
#### CHAPTER 5 오차역전파법 
#### 일자 : 2020-08-16

- 수치미분은 구현이 쉽지만 계산 시간이 오래걸린다. 
- 가중치 매개변수의 기울기를 효율적으로 계산하는 오차역전파법!

---

## 덧셈, 곱셈의 역전파 => 계산 그래프를 사용해서 계산 과정을 보면 쉽다. 

- 덧셈의 역전파에서는 상류의 값을 그대로 흘려보내서 순방향 입력 신호의 값이 필요하지 않다.
- 곱섬의 역전파는 상류의 값에 순방향 입력 신호를 서로 바꿔서 곱한 값을 흘려보낸다.  

## 곱셈 계층 


In [2]:
class MulLayer:
  
  def __init(self):
    self.x = none
    self.y = none
  
  def forward(self,x,y):
    self.x = x
    self.y = y
    out = x * y

    return out
  
  def backward(self, d_out): # 상류의 값(미분 값)에 순방향 입력 신호를 서로 바꿔서 곱한 값을 흘려보낸다. 
    d_x = d_out * self.y
    d_y = d_out * self.x

    return d_x, d_y 


## 곱셈 계층 순전파 

In [3]:
apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple,apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(apple_price)
print(price)

200
220.00000000000003


## 곱셈 계층 역전파 

In [4]:
dprice = 1

dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


## 덧셈 계층

In [5]:
class AddLayer:

  def __init__(self):
    pass

  def forward(self,x,y):
    out = x + y
    return out

  def backward(self, d_out):
    d_x = d_out * 1
    d_y = d_out * 1
    return d_x, d_y

## 사과 2개 귤 3개 사는 상황 구현 

In [6]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

dprice = 1

mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
mul_tax_layer = MulLayer()
add_apple_orange_layer = AddLayer()

apple_price = mul_apple_layer.forward(apple,apple_num)
orange_price = mul_orange_layer.forward(orange,orange_num)
fruit_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(fruit_price, tax)

print("**** 순전파 ****\n")
print("apple_price : {} \n orange_price : {} \n fruit_price : {} \n price : {}\n".format(apple_price, orange_price, fruit_price, price))


dfruit_price, dtax = mul_tax_layer.backward(dprice)
dapple_price, dorange_price = add_apple_orange_layer.backward(dfruit_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)
print("**** 역전파 ****\n")
print("dapple : {} \n dapple_num : {} \n dapple_price : {} \n dorange : {} \n dorange_num : {} \n dorange_price : {} \n dfruit_price : {} \n dprice : {}".format(dapple, dapple_num ,dapple_price, dorange, dorange_num, dorange_price, dfruit_price, dprice))



**** 순전파 ****

apple_price : 200 
 orange_price : 450 
 fruit_price : 650 
 price : 715.0000000000001

**** 역전파 ****

dapple : 2.2 
 dapple_num : 110.00000000000001 
 dapple_price : 1.1 
 dorange : 3.3000000000000003 
 dorange_num : 165.0 
 dorange_price : 1.1 
 dfruit_price : 1.1 
 dprice : 1


## 활성화 함수 계층 구현하기 

### 1. ReLU 계층 
- ReLU 순전파
  - 입력인 x가 0보다 크면 x가 그대로 전달되고, 0보다 작으면 전달 되지 않는다. (0이 전달 되는 것과 같다) 
- ReLU 역전파  
  - 순전파 때의 입력인 x가 0보다 크면 상류의 값을 그대로 하류로 흘린다. 
  - 순전파 때 x가 0 이하면 역전파 때는 하류로 신호를 보내지 않는다. 

In [7]:
class ReLU:
  def __init__(self):
    self.x = none
  
  def forward(self, x):
    self.x = x
    
    return self.x
  
  def backward(self, d_out):
    if self.x > 0:
      return 1
    else :
      return 0

내가 생각했던 코드... 하지만 어딘가 이상하다 

masking을 해야 된다! 

In [8]:
import  numpy as np 

x = np.array([[1.0,-0.5],[-2.0, 3.0]])
print(x)

mask = (x <= 0)
print(mask)


[[ 1.  -0.5]
 [-2.   3. ]]
[[False  True]
 [ True False]]


In [9]:
x[mask] = 0

In [10]:
x

array([[1., 0.],
       [0., 3.]])


  - True가 0이 된다. 즉, 0보다 작은 수가 0이 된다.
  - masking을 해서 0보다 작은 수를 0으로 만들고 0보다 큰 수를 1로 만든다. 

In [11]:
class ReLU:
  def __init__(self):
    self.mask = none # 초기화 시켜주기 
  
  def forward(self, x):
    self.mask = (x <= 0)
    out = x.copy()
    out[maxk] = 0

    return out
  
  def backward(self, d_out):
    d_out[self.mask] = 0
    d_x = d_out

    return d_x

## Sigmoid 계층 

- 순전파와 역전파를 직접 계산 그래프를 그리면 더 이해하기 쉽다. 

그림 첨후 할 예정 ! 

- sigmoid 계산을 할때 중간 과정을 하나씩 다 안 계산해도 한번에 순전파의 출력만을 가지고 계산할 수 있다. 

In [12]:
class Sigmoid:

  def __init__(self):
    self.out = None
  
  def forward(self, x):
    self.out = 1 / (1 + np.exp(-x))

    return self.out
  
  def backward(self, d_out):
    d_x = d_out * (1 - self.out) * self.out

    return d_x

- 순전파의 출력을 변수 out에 저장해서 역전파를 계산할 때 사용한다. 

## Affine/Softmax 계층 구현하기

---

## Affine 계층 

- 신경망의 순전파 때 수행하는 행렬의 내적을 affine transformation이라고 한다. 

In [19]:
X = np.random.rand(2) 
W = np.random.rand(2,3)
B = np.random.rand(3)

print('X.shape :',X.shape)
print('W.shape :',W.shape)
print('B.shape :',B.shape)

Y = np.dot(X,W) + B
print('Y.shape :',Y.shape)

X.shape : (2,)
W.shape : (2, 3)
B.shape : (3,)
Y.shape : (3,)


## 배치용 Affine 계층 
- 순전파의 편향 덧셈은 각각의 원소에 더해진다.
- 역전파의 경우 각 데이터의 역전파 값이 평향의 원소에 모여야된다. 열방향 (axis = 0)에 대해서 총합을 구한다.

In [20]:
dY = np.array([[1,2,3],[4,5,6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
dB = np.sum(dY,axis = 0)
dB

array([5, 7, 9])

편향을 다시 (3,)로 만들어야 다시 순전파를 할때 사용할 수 있다. 

In [23]:
class Affine:

  def __init__(self):

    self.W = W
    self.b = b
    self.x = None
    self.dW = None
    self.db = None
  
  def forward(self,x):
    self.x = x
    out = np.dot(x,self.W) + self.b
    return out

  def backward(self,d_out):

    d_x = np.dot(d_out,self.W.T)
    self.dW = np.dot(self.x.T,d_out)
    self.db = np.sum(d_out, axis = 0) # 역전파 값인 d_out가 열방향으로 모여서 편향이 된다. 

    return d_x


하지만 위의 식은 4차원 데이터(텐서)인 경우는 고려하지 않았다. 

In [26]:
x = np.array([[[[1,2,3],[2,3,4],[3,4,5]],[[1,2,3],[2,3,4],[3,4,5]]]])
x.shape

(1, 2, 3, 3)

In [27]:
x1 = x.reshape(x.shape[0],-1)
x1.shape

(1, 18)

## Softmax_with_Loss 계층

