<a href="https://colab.research.google.com/github/KIMDOKYOUNG/DeepLearning/blob/master/2_chapter1/chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## 밑바닥부터 시작하는 딥러닝 2 뽀개기
#### CHAPTER 1 신경망 복습
#### 일자 : 2020-08-25

- 벡터의 내적과 행렬의 곱 


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.matmul(a,b)

32

In [5]:
a = np.array([[1,2,],[3,4]])
b = np.array([[5,6],[7,8]])

print(a)
print(b)

np.matmul(a,b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [6]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

- 2차원 데이터에 대해서는 matmul이 dot과 같은 역할을 한다. 

## 비선형 함수 
- 신경망에 비선형 효과를 부여한다.
- 신경망의 자유도를 높이는 것 

### 시그모이드 함수 

$$ \sigma \left ( x\right ) = \frac{1}{1+\exp(-x)}$$

- 임의의 실수를 입력받아 0에서 1사이의 실수를 출력한다. 


In [7]:
def sigmoid(x):
  return 1/ (1+np.exp(-x))

In [8]:
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)
h = np.matmul(x,W1) + b1

In [9]:
output = sigmoid(h)

In [10]:
print(output)

[[0.53185402 0.19895101 0.29233301 0.56424588]
 [0.23013413 0.81625094 0.28827955 0.43487476]
 [0.23017992 0.38885546 0.26676329 0.48020772]
 [0.52272234 0.96068853 0.34628676 0.45513601]
 [0.81215876 0.96868073 0.39216041 0.51355015]
 [0.15115641 0.22711049 0.24539949 0.47419785]
 [0.35194018 0.85872193 0.30866615 0.45511234]
 [0.22279856 0.9338767  0.30038781 0.40647176]
 [0.80154868 0.96243383 0.38751263 0.514799  ]
 [0.10422314 0.2475268  0.23610769 0.45181202]]


- 노드수 : 2 => 4 
- 입력 10개 배치의 2차원 데이터
- 출력 10개 배치의 4차원 데이터 

In [11]:
x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x,W1) + b1
a = sigmoid(h)
output = np.matmul(a,W2) + b2

In [12]:
print(output)

[[ 0.23938669 -1.82207795  0.98890554]
 [ 0.41120979 -1.3930307   1.87736178]
 [-0.24725362 -1.6605354   0.77304615]
 [-0.0205585  -1.73930299  0.8499586 ]
 [ 0.58809847 -1.36624429  1.97719851]
 [-0.07404465 -2.06969896  0.05245975]
 [-0.73375689 -2.1083764  -0.2974667 ]
 [-0.56520448 -2.12304472 -0.41698074]
 [-0.00632352 -2.10671868  0.06482201]
 [ 0.63082719 -1.74514356  1.53702914]]


- 노드수 : 2 => 4 => 3
- 입력 : 2차원 데이터 10개 
- 히든 레이어 : 4차원
- 출력 : 3차원 데이터 10개 

## 계층으로 클래스화 및 순전파 구현 

In [13]:
class Sigmoid:
  def __init__(self):
    self.params = []
  
  def forward(self, x):
    return 1 /(1 +np.exp(-x))

class Affine : 
  def __init__(self,W,b):
    self.params = [W,b]
  
  def forward(self, x):
    W,b = self.params
    out = np.matmul(x,W) + b
    return out 
  

In [14]:
class TwoLayerNet:
  def __init__(self,input_size, hidden_size, output_size):
    I,H,O = input_size, hidden_size, output_size
    
    # 가중치와 편향 초기화 
    W1 = np.random.randn(I,H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H,O)
    b2 = np.random.randn(O)

    self.layers = [Affine(W1,b1), Sigmoid(), Affine(W2,b2)]

    self.params = []
    for layer in self.layers:
      self.params += layer.params
    
  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    return x
  


- params에 모든 학습 매개변수를 저장한다.
- 파이썬의 + 연산자는 리스트들을 결합시켜준다. 


In [15]:
a = [1,2]
a += [3,4]
print(a)

[1, 2, 3, 4]


In [16]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [17]:
print(s)

[[-2.97257757  2.09269337 -0.3765415 ]
 [-2.56231852  2.32346041 -1.32429687]
 [-2.38870751  2.12033145 -1.09396719]
 [-2.37425863  1.81588165 -0.47214207]
 [-3.08361461  2.40652617 -0.48751534]
 [-1.42177968  1.08662874 -0.32676396]
 [-3.01975119  2.12762608 -0.33957989]
 [-1.52579144  1.33521668 -0.57498497]
 [-2.47440893  2.28358962 -1.33386889]
 [-1.71333153  1.35007089 -0.30199035]]


## 신경망의 학습

### 손실함수 
- 다중 클래스 분류 신경망에선 교차 엔트로피 오차를 이용한다. 
  - 각 클래스의 확률과 정답 레이블을 이용해 구할 수 있다. 

In [19]:
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)# 오버플로 대책
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y 

In [18]:
def cross_entropy_error(y,t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)

  batch_size = y.shape[0]

  return -np.sum(t*np.log(y)) / batch_size

## 계산 그래프 
- 덧셈 노드 
  - 역전파 : 하류로 상류의 값에 1을 곱한 값을 흘린다. 
- 곱셈 노드 
  - 역전파 : 상류로부터 받은 기울기에 순전파 시 입력을 서로 바꾼 값을 곱한다. 
- 분기 노드
  - 단순히 선이 두개로 나뉘어지는 것 
  - 같은 값이 복제되어 분기된다. x => x,x
  - 역전파 : 상류에서 온 기울기들의 합 
- repeat 노드 
  - N개로의 분기 
  - 역전파 : n개의 기울기를 모두 더해서 구한다


In [20]:
D , N = 4,5 # 길이가 D, N개로 복제 

x = np.random.randn(1,D) # 입력
y = np.repeat(x, N, axis = 0) # 순전파 

dy = np.random.randn(N,D) # 무작위 기울기 
dx = np.sum(dy,axis = 0, keepdims = True) # 2차원 배열의 차원수를 유지한다. 

In [23]:
print(x)
print(y)
print(dy)
print(dx)

[[-0.26956309 -0.96651419  0.00397626  0.60498015]]
[[-0.26956309 -0.96651419  0.00397626  0.60498015]
 [-0.26956309 -0.96651419  0.00397626  0.60498015]
 [-0.26956309 -0.96651419  0.00397626  0.60498015]
 [-0.26956309 -0.96651419  0.00397626  0.60498015]
 [-0.26956309 -0.96651419  0.00397626  0.60498015]]
[[-0.76611616  0.53346581 -0.4970544  -0.7906332 ]
 [-1.24291929 -0.44431252  0.70441559 -2.2578304 ]
 [ 1.98347052 -0.45476657 -1.39410258 -2.13197922]
 [-0.2131303  -0.18997188  0.82229844 -0.67770857]
 [-0.25981616  0.34441188 -0.48779967 -1.16462387]]
[[-0.49851139 -0.21117327 -0.85224262 -7.02277526]]


- sum 노드 (범용 덧셈 노드) 
  - repeat 노드와 정반대 

In [24]:
D , N = 4,5 # 길이가 D, N개로 복제 

x = np.random.randn(N,D) # 입력
y = np.sum(x,axis = 0, keepdims = True) # 순전파,  2차원 배열의 차원수를 유지한다. 


dy = np.random.randn(1,D) # 무작위 기울기 
dx = np.repeat(dy,N, axis = 0) # 역전파 


In [25]:
print(x)
print(y)
print(dy)
print(dx)

[[ 0.6814466  -0.29621529 -0.87860126  1.33296459]
 [-0.65608012 -0.85367264 -1.07821542 -0.1630414 ]
 [ 0.54806439  0.92722317  0.48491348 -1.63345536]
 [ 1.06009132  1.22516834 -0.70910709  1.35213175]
 [-1.28639792  1.60237075  0.68543966 -0.30839567]]
[[ 0.34712426  2.60487433 -1.49557063  0.5802039 ]]
[[-0.85702726 -1.21430886  0.66709139 -1.57436018]]
[[-0.85702726 -1.21430886  0.66709139 -1.57436018]
 [-0.85702726 -1.21430886  0.66709139 -1.57436018]
 [-0.85702726 -1.21430886  0.66709139 -1.57436018]
 [-0.85702726 -1.21430886  0.66709139 -1.57436018]
 [-0.85702726 -1.21430886  0.66709139 -1.57436018]]


- MatMul 노드 

  $y = xW$를 사용해서 MatMul 노드를 설명해볼께요!
  - x.shape = (1*D)
  - W.shape = (D *H)
  - y.shape = (1*H)
  - x의 i번째 원소에 대한 미분 $\frac{\partial L}{\partial x_i}$는 다음과 같다.
  $$\frac{\partial L}{\partial  x_i}  = \sum_{j}\frac{\partial L}{\partial y_i}\frac{\partial y_i}{\partial x_i}$$
  - $\frac{\partial L}{\partial x_i}$은 $x_i$를 조금 변화 시켰을때 $L$이 얼마나 변할 것인가라는 변화의정도를 나타낸다. 
  - $x_i$에서 $L$에 이르는 연쇄 법칙의 경로는 여러개가 있고, 그 총합은  $\frac{\partial L}{\partial x_i}$이 된다. 
  - 곱셈 노드의 경우에 따라 $\frac{\partial L}{\partial x_i} = W_{ij}$가 성립하므로 다음과 같아진다.
    $$\frac{\partial L}{\partial  x_i}  = \sum_{j}\frac{\partial L}{\partial y_i}\frac{\partial y_i}{\partial x_i} = \sum_{j}\frac{\partial L}{\partial y_i}W_{ij}$$
  - $\frac{\partial L}{\partial  x_i}$는 벡터 $\frac{\partial L}{\partial y_i}$과 $W$의 $i$행 벡터의 내적으로 구해짐을 알 수 있다. 그러므로 다음 관계식을 유도할 수 있다.
  $$\frac{\partial L}{\partial  x}  =\frac{\partial L}{\partial  y}W^T$$ 
  - $\frac{\partial L}{\partial  x} $는 행렬의 곱을 사용해 단번에 구할 수 있다.


  - x에 N개의 데이터가 담겨 있다면 
    - x.shape = (N*D)
    - W.shape = (D *H)
    - y.shape = (N*H)
    - 역전파 식은 아래와 같다
   $$\frac{\partial L}{\partial  x}   \quad =  \quad \frac{\partial L}{\partial  y} \qquad W^T$$ 
  $$$$
  $$ N*D  \qquad N*H  \qquad H*D$$
  $$$$
  $$\frac{\partial L}{\partial  W}   \quad =  \quad  X^T  \quad \frac{\partial L}{\partial  y} $$ 
  $$$$
  $$ D*H  \qquad D*N  \qquad N*H$$
  

In [26]:
-class MatMul:
  def __init__(self,W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.x = None
  
  def forward(self,x):
    W, = self.params
    out = np.matmul(x,W)
    self.x = x

    return out

  def backward(self, dout):
    W, = self.params
    dx = np.matmul(dout,W.T)
    dW = np.matmul(self.x.T, dout)
    self.grads[0][...] = dW # 깊은 복사 

    return dx

- Sigmoid 계층

$$ y = \frac{1}{1+\exp(-x)}$$

$$ \frac{\partial L}{\partial y} y	\left (1-y \right )$$


In [27]:
class Sigmoid:
  def __init__(self):
    self.params, self.grads = [],[]
    self.out = None
  
  def forward(self,x):
    out = 1/ (1 + np.exp(-x))
    self.out = out
    return out

  def backward(self,dout):
    dx = dout * (1.0- self.out) * self.out
    return dx